spring.application.name=user_auth
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-snowy-waterfall-axsifi9v-pooler.c-4.us-east-2.aws.neon.tech/auth_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1fv0cPupJRSd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== JWT =====
# TODO: da secret wahmy khales, momnoo3 y-t7at zy da fe production
# lazem yb2a env variable w yb2a 256-bit (32+ byte) random string
app.jwt.secret=asdfasdfasdccvsdfv1234567891loay
# access token: 15 minutes (bl millisecond)
app.jwt.access-token-expiration-ms=900000
# refresh token: 7 days (bl millisecond)
app.jwt.refresh-token-expiration-ms=604800000

# ===== Swagger / OpenAPI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs