spring.application.name=api_gateway

server.port=8080
app.jwt.secret=asdfasdfasdccvsdfv1234567891loay
app.jwt.issuer=recruitment-auth

spring.cloud.gateway.server.webflux.routes[0].id=user-auth
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=candidate
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/candidates/**

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=unrestricted

logging.level.org.springframework.cloud.gateway=DEBUG